# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
source 'https://github.com/awasthi027/ios-spec.git'

def sdkpod(subspec)
  pod 'LearningSubspecSDK/' + subspec, :path => 'Frameworks/LearningSubspecSDK'
end

target 'UITestPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UITestPOC
  sdkpod 'AutomationSupports'

  target 'UITestPOCTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'UITestPOCUITests' do
    pod 'XCTestExtension', :path => 'Frameworks/XCTestExtension'
  end

end
