# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CertsOpenSSL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CertsOpenSSL

  pod 'OpenSSL-Universal'

  target 'CertsOpenSSLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CertsOpenSSLUITests' do
    # Pods for testing
  end

end
