# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
source 'https://github.com/awasthi027/ios-spec.git'

def sdkpod(subspec)
  pod 'LearningSubspecSDK/' + subspec, :path => 'Frameworks/LearningSubspecSDK'
  
end

target 'ExtensionPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 

  # Pods for ExtensionPOC

  target 'ExtensionPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExtensionPOCUITests' do
    # Pods for testing

  end

end

target 'ShareExt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LearningSubspecSDK', :path => 'Frameworks/LearningSubspecSDK' # It will allow to access default podspecs
  sdkpod 'ExtensionSafeAPI' # It will allow you to access only extension Safe API spec
end


