# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) { }
  system("sh Scripts/invokeDownloadCommand.sh tempDir https://www.clickdimensions.com/links/TestPDFfile.pdf")
end


target 'PodsRaD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodsRaD

end



